#!/bin/bash

source .env

gcloud functions deploy $CF_FUNCTION_NAME \
--gen2 \
--trigger-http \
--region=$CF_REGION \
--runtime=$CF_RUNTIME \
--entry-point=$CF_ENTRY_POINT \
--memory=$CF_MEMORY \
--service-account=$CF_SVC_ACCT_EMAIL \
--no-allow-unauthenticated \
--set-env-vars \
GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID",\
GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET",\
GMAIL_API_REFRESH_TOKEN="$GMAIL_API_REFRESH_TOKEN",\
DRIVE_API_REFRESH_TOKEN="$DRIVE_API_REFRESH_TOKEN",\
DRIVE_EMAIL_MESSAGES_FOLDER_ID="$DRIVE_EMAIL_MESSAGES_FOLDER_ID",\
DRIVE_EMAIL_ATTACHMENTS_FOLDER_ID="$DRIVE_EMAIL_ATTACHMENTS_FOLDER_ID",\
NOTION_API_TOKEN="$NOTION_API_TOKEN",\
NOTION_API_EMAILS_DB_ID="$NOTION_API_EMAILS_DB_ID",\
GMAIL_SYNC_LABEL="$GMAIL_SYNC_LABEL"
